version: '1.0'

services:
  mysql:
    image: mysql:8
    container_name: mysql-jdbc-connector
    restart: unless-stopped
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: jellybeans
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: